// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDniGS3aByahLhxSoMO0OPg3dZgooZonN8',
    appId: '1:897855879290:web:8793f438ef2619f45aa3c3',
    messagingSenderId: '897855879290',
    projectId: 'underthec-6d89b',
    authDomain: 'underthec-6d89b.firebaseapp.com',
    storageBucket: 'underthec-6d89b.appspot.com',
    measurementId: 'G-85MWWJQ8TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtmzHBCvHUDnczhxZv8AW6c2ftV63RjCk',
    appId: '1:897855879290:android:23426b565ef81e695aa3c3',
    messagingSenderId: '897855879290',
    projectId: 'underthec-6d89b',
    storageBucket: 'underthec-6d89b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_PZWjvjVVOU-FmgZQwnqQpzhUqzRhjc',
    appId: '1:897855879290:ios:22271d624a09af295aa3c3',
    messagingSenderId: '897855879290',
    projectId: 'underthec-6d89b',
    storageBucket: 'underthec-6d89b.appspot.com',
    iosClientId: '897855879290-8v4e159kkpmvtro92ire2mt7j63p6g8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.underTheCApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_PZWjvjVVOU-FmgZQwnqQpzhUqzRhjc',
    appId: '1:897855879290:ios:dea6887bc68959845aa3c3',
    messagingSenderId: '897855879290',
    projectId: 'underthec-6d89b',
    storageBucket: 'underthec-6d89b.appspot.com',
    iosClientId: '897855879290-10ogasi1tqis0aovp5sl29sfih3uegcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.underTheCApp.RunnerTests',
  );
}
